version: '3'

services:
  frontend:
    image: cutartsis-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
    - /data/frontend-images:/frontend-images
    - /root/certs-data/:/data/letsencrypt/
    - /etc/letsencrypt/:/etc/letsencrypt/