version: '3'

services:
  frontend:
    image: cutartsis-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/frontend-images/pictures_processed/:/images
      - /root/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    configs:
      container_name: frontend
